/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Fernando
 * Created: 16-11-2016
 */

create table ASIGNATURAS_EJECUCION 
(
   ID_CARRERA            integer                        not null, 
   ID_RAMO               smallint                       not null UNIQUE, 
   NIVEL_RAMO            smallint                       not null,
   NOMBRE_RAMO           varchar(50)                    not null
);

INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 1, 1, 'Cálculo I');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 2, 1, 'Álgebra I');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 3, 1, 'Física I');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 4, 1, 'Taller de Desarrollo Personal e Integral');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 5, 1, 'Introducción a la Ingeniería');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 6, 1, 'Métodos de Estudio');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 7, 2, 'Cálculo II');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 8, 2, 'Álgebra II');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 9, 2, 'Física II');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 10, 2, 'Fundamentos de Computación y Programación');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 11, 2, 'Química General');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 12, 3, 'Análisis Estadístico');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 13, 3, 'Ecuaciones Diferenciales y Métodos Numéricos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 14, 3, 'Electricidad y Magnetismo');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 15, 3, 'Comunicación Efectiva');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 16, 3, 'Inglés I');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 17, 3, 'Métodos de Programación');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 18, 4, 'Fundamentos de Economía');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 19, 4, 'Inglés II');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 20, 4, 'Paradigmas de Programación');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 21, 4, 'Análisis de Algoritmos y Estructura de Datos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 22, 4, 'Ingeniería de Sistemas');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 23, 4, 'Estructura de Computadores');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 24, 5, 'Inglés III');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 25, 5, 'Fundamentos de Ingeniería en Software');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 26, 5, 'Evaluación y Gestión de Proyectos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 27, 5, 'Informática y Sociedad');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 28, 5, 'Sistemas de Información');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 29, 5, 'Diseño de Base de Datos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 30, 5, 'Organización de Computadores');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 31, 6, 'Inglés IV');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 32, 6, 'Sistemas Operativos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 33, 6, 'Taller de Bases de Datos');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 34, 6, 'Administración y Gestión Informática');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 35, 6, 'Técnicas de Ingeniería de Software');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 36, 6, 'Redes Computacionales');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 37, 7, 'Proyecto de Ingeniería en Software');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 38, 7, 'Tópicos de Especialidad I');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 39, 7, 'Tópicos de Especialidad II');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 40, 7, 'Tópicos de Especialidad III');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 41, 7, 'Seminario de Computación e Informática');
INSERT INTO ASIGNATURAS_EJECUCION (ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (1, 42, 8, 'Trabajo de Titulación');

