/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Fernando
 * Created: 16-11-2016
 */

create table ASIGNATURAS_CIVIL 
(
   ID_CARRERA            smallint                       not null,
   ID_RAMO               smallint                       not null UNIQUE, 
   NIVEL_RAMO            smallint                       not null,
   NOMBRE_RAMO           varchar(50)                    not null
);

INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 1, 1, 'Cálculo I');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 2, 1, 'Álgebra I');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 3, 1, 'Física I');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 4, 1, 'Taller de Desarrollo Personal e Integral');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 5, 1, 'Introducción a la Ingeniería');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 6, 1, 'Métodos de Estudio');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 7, 2, 'Cálculo II');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 8, 2, 'Álgebra II');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 9, 2, 'Física II');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 10, 2, 'Fundamentos de Computación y Programación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 11, 2, 'Química General');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 12, 3, 'Fundamentos de Economía');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 13, 3, 'Ecuaciones Diferenciales');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 14, 3, 'Electricidad y Magnetismo');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 15, 3, 'Comunicación Efectiva');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 16, 3, 'Inglés I');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 17, 3, 'Métodos de Programación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 18, 4, 'Cálculo III');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 19, 4, 'Inglés II');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 20, 4, 'Paradigmas de Programación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 21, 4, 'Análisis de Algoritmos y Estructura de Datos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 22, 4, 'Análisis Estadístico');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 23, 4, 'Estructura de Computadores');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 24, 5, 'Inglés III');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 25, 5, 'Fundamentos de Ingeniería de Software');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 26, 5, 'Ingeniería de Sistemas');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 27, 5, 'Algoritmos Avanzados');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 28, 5, 'Organización de Computadores');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 29, 5, 'Diseño de Base de Datos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 30, 6, 'Inglés IV');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 31, 6, 'Sistemas Operativos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 32, 6, 'Taller de Bases de Datos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 33, 6, 'Algoritmos Numéricos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 34, 6, 'Procesamiento de Lenguajes Formales');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 35, 6, 'Antropología e Ingeniería');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 36, 7, 'Inferencia y Modelos Estadísticos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 37, 7, 'Redes de Computadores');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 38, 7, 'Lógica y Teoría de la Computación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 39, 7, 'Macroeconomía y Globalización');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 40, 7, 'Métodos de Ingeniería de Software');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 41, 8, 'Métodos de Optimización');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 42, 8, 'Análisis de Datos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 43, 8, 'Sitemas de Comunicación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 44, 8, 'Finanzas y Contabilidad');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 45, 8, 'Administración de Proyectos de Software');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 46, 9, 'Ingeniería y Sociedad');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 47, 9, 'Modelación y Simulación');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 48, 9, 'Sistemas Distribuidos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 49, 9, 'Evaluación de Proyectos');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 50, 9, 'Taller de Ingeniería de Software');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 51, 10, 'Tópicos de Especialidad I');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 52, 10, 'Tópicos de Especialidad II');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 53, 10, 'Tópicos de Especialidad III');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 54, 10, 'Seguridad y Auditoría Informática');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 55, 10, 'Proyecto de Ingeniería Informática');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 56, 11, 'Dirección y Gestión de Empresas');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 57, 11, 'Tópicos de Especialidad IV');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 58, 11, 'Tópicos de Especialidad V');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 59, 11, 'Tópicos de Especialidad VI');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 60, 11, 'Seminario de Informática');
INSERT INTO ASIGNATURAS_CIVIL(ID_CARRERA, ID_RAMO, NIVEL_RAMO, NOMBRE_RAMO) VALUES (2, 61, 12, 'Trabajo de Titulación');
