/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTextField;
import Controladores.ControladorMiniJuegoAhorcado;

/**
 *
 * @author Fernando
 */
public class VistaMiniJuegoAhorcado extends javax.swing.JDialog {
    ControladorMiniJuegoAhorcado conahor;
   /**
     * Creates new form VistaAhorcado
     */
    public VistaMiniJuegoAhorcado(java.awt.Frame parent, boolean modal, ControladorMiniJuegoAhorcado conahor) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
        this.conahor = conahor;
    }

    public void addListeners(ActionListener al){
        //A cada uno de los botones que componen la vista del minijuego se le agrega un ActionListener
        botonA.addActionListener(al);
        botonB.addActionListener(al);
        botonC.addActionListener(al);
        botonD.addActionListener(al);
        botonE.addActionListener(al);
        botonF.addActionListener(al);
        botonG.addActionListener(al);
        botonH.addActionListener(al);
        botonI.addActionListener(al);
        botonJ.addActionListener(al);
        botonK.addActionListener(al);
        botonL.addActionListener(al);
        botonM.addActionListener(al);
        botonN.addActionListener(al);
        botonÑ.addActionListener(al);
        botonO.addActionListener(al);
        botonP.addActionListener(al);
        botonQ.addActionListener(al);
        botonR.addActionListener(al);
        botonS.addActionListener(al);
        botonT.addActionListener(al);
        botonU.addActionListener(al);
        botonV.addActionListener(al);
        botonW.addActionListener(al);
        botonX.addActionListener(al);
        botonY.addActionListener(al);
        botonZ.addActionListener(al);
        botonNuevaPartida.addActionListener(al);
        botonSalir.addActionListener(al); 
    }
    
    public void activarBotones(){
         botonA.setEnabled(true);
         botonB.setEnabled(true);
         botonD.setEnabled(true);
         botonC.setEnabled(true);
         botonE.setEnabled(true);
         botonF.setEnabled(true);
         botonG.setEnabled(true);
         botonH.setEnabled(true);
         botonI.setEnabled(true);
         botonJ.setEnabled(true);
         botonK.setEnabled(true);
         botonL.setEnabled(true);
         botonM.setEnabled(true);
         botonN.setEnabled(true);
         botonÑ.setEnabled(true);
         botonO.setEnabled(true);
         botonP.setEnabled(true);
         botonQ.setEnabled(true);
         botonR.setEnabled(true);
         botonS.setEnabled(true);
         botonT.setEnabled(true);
         botonU.setEnabled(true);
         botonV.setEnabled(true);
         botonW.setEnabled(true);
         botonX.setEnabled(true);
         botonY.setEnabled(true);
         botonZ.setEnabled(true);
    }
    
    public void desactivarBotones(){
         botonA.setEnabled(false);
         botonB.setEnabled(false);
         botonD.setEnabled(false);
         botonC.setEnabled(false);
         botonE.setEnabled(false);
         botonF.setEnabled(false);
         botonG.setEnabled(false);
         botonH.setEnabled(false);
         botonI.setEnabled(false);
         botonJ.setEnabled(false);
         botonK.setEnabled(false);
         botonL.setEnabled(false);
         botonM.setEnabled(false);
         botonN.setEnabled(false);
         botonÑ.setEnabled(false);
         botonO.setEnabled(false);
         botonP.setEnabled(false);
         botonQ.setEnabled(false);
         botonR.setEnabled(false);
         botonS.setEnabled(false);
         botonT.setEnabled(false);
         botonU.setEnabled(false);
         botonV.setEnabled(false);
         botonW.setEnabled(false);
         botonX.setEnabled(false);
         botonY.setEnabled(false);
         botonZ.setEnabled(false);
    }

            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevaPartida = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelPanelUsuario = new javax.swing.JLabel();
        labelPanelCPU = new javax.swing.JLabel();
        panelLetras = new javax.swing.JPanel();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        botonE = new javax.swing.JButton();
        botonF = new javax.swing.JButton();
        botonG = new javax.swing.JButton();
        botonH = new javax.swing.JButton();
        botonI = new javax.swing.JButton();
        botonJ = new javax.swing.JButton();
        botonK = new javax.swing.JButton();
        botonL = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        botonN = new javax.swing.JButton();
        botonÑ = new javax.swing.JButton();
        botonO = new javax.swing.JButton();
        botonP = new javax.swing.JButton();
        botonQ = new javax.swing.JButton();
        botonR = new javax.swing.JButton();
        botonS = new javax.swing.JButton();
        botonT = new javax.swing.JButton();
        botonU = new javax.swing.JButton();
        botonV = new javax.swing.JButton();
        botonW = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        botonY = new javax.swing.JButton();
        botonZ = new javax.swing.JButton();
        panelPalabra = new javax.swing.JPanel();
        labelErroresCPU = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelErroresUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textCPU = new javax.swing.JTextField();
        labelDinero = new javax.swing.JLabel();
        textDinero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelFiguraAhorcadoCPU = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelFiguraAhorcadoUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("El Ahorcado");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonNuevaPartida.setBackground(new java.awt.Color(0, 0, 0));
        botonNuevaPartida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonNuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoVerde.png"))); // NOI18N
        botonNuevaPartida.setText("Nueva partida");
        botonNuevaPartida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(botonNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 40));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("El Ahorcado");
        labelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        labelTitulo.setOpaque(true);
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 410, 60));

        botonSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoRojo.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 220, 40));

        labelPanelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        labelPanelUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPanelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelPanelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPanelUsuario.setText("PANEL USUARIO");
        labelPanelUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPanelUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPanelUsuario.setOpaque(true);
        getContentPane().add(labelPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 450, 20));

        labelPanelCPU.setBackground(new java.awt.Color(0, 0, 0));
        labelPanelCPU.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPanelCPU.setForeground(new java.awt.Color(255, 255, 255));
        labelPanelCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPanelCPU.setText("PANEL CPU");
        labelPanelCPU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPanelCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPanelCPU.setOpaque(true);
        getContentPane().add(labelPanelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 450, 20));

        panelLetras.setBackground(new java.awt.Color(255, 255, 255));
        panelLetras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLetras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonA.setText("A");
        panelLetras.add(botonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 60, 30));

        botonB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonB.setText("B");
        panelLetras.add(botonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 5, 60, 30));

        botonC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonC.setText("C");
        panelLetras.add(botonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 5, 60, 30));

        botonD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonD.setText("D");
        panelLetras.add(botonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 5, 60, 30));

        botonE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonE.setText("E");
        panelLetras.add(botonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, 60, 30));

        botonF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonF.setText("F");
        panelLetras.add(botonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 5, 60, 30));

        botonG.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonG.setText("G");
        panelLetras.add(botonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 5, 60, 30));

        botonH.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonH.setText("H");
        panelLetras.add(botonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 5, 60, 30));

        botonI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonI.setText("I");
        panelLetras.add(botonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 5, 60, 30));

        botonJ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonJ.setText("J");
        panelLetras.add(botonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 60, 30));

        botonK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonK.setText("K");
        panelLetras.add(botonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 60, 30));

        botonL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonL.setText("L");
        panelLetras.add(botonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 35, 60, 30));

        botonM.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonM.setText("M");
        panelLetras.add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 35, 60, 30));

        botonN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonN.setText("N");
        panelLetras.add(botonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 35, 60, 30));

        botonÑ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonÑ.setText("Ñ");
        panelLetras.add(botonÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 35, 60, 30));

        botonO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonO.setText("O");
        panelLetras.add(botonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 35, 60, 30));

        botonP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonP.setText("P");
        panelLetras.add(botonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, 60, 30));

        botonQ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonQ.setText("Q");
        panelLetras.add(botonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 35, 60, 30));

        botonR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonR.setText("R");
        panelLetras.add(botonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 60, 30));

        botonS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonS.setText("S");
        panelLetras.add(botonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 65, 60, 30));

        botonT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonT.setText("T");
        botonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTActionPerformed(evt);
            }
        });
        panelLetras.add(botonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 65, 60, 30));

        botonU.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonU.setText("U");
        panelLetras.add(botonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 65, 60, 30));

        botonV.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonV.setText("V");
        panelLetras.add(botonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 65, 60, 30));

        botonW.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonW.setText("W");
        panelLetras.add(botonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 65, 60, 30));

        botonX.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonX.setText("X");
        panelLetras.add(botonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 65, 60, 30));

        botonY.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonY.setText("Y");
        panelLetras.add(botonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 65, 60, 30));

        botonZ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonZ.setText("Z");
        panelLetras.add(botonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 65, 60, 30));

        getContentPane().add(panelLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 560, 100));

        panelPalabra.setBackground(new java.awt.Color(255, 255, 255));
        panelPalabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelPalabra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelErroresCPU.setBackground(new java.awt.Color(255, 255, 255));
        labelErroresCPU.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelErroresCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErroresCPU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelErroresCPU.setOpaque(true);
        panelPalabra.add(labelErroresCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 25, 210, 25));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Desaciertos CPU:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        panelPalabra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 170, 25));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Palabra:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        panelPalabra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 25));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Desaciertos Usuario:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        panelPalabra.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 25));

        labelErroresUsuario.setBackground(new java.awt.Color(255, 255, 255));
        labelErroresUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelErroresUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErroresUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelErroresUsuario.setOpaque(true);
        panelPalabra.add(labelErroresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 210, 25));

        textUsuario.setEditable(false);
        textUsuario.setBackground(new java.awt.Color(0, 0, 0));
        textUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textUsuario.setText("????????????????");
        textUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPalabra.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, 25));

        textCPU.setBackground(new java.awt.Color(0, 0, 0));
        textCPU.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        textCPU.setForeground(new java.awt.Color(255, 255, 255));
        textCPU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCPU.setText("????????????????");
        textCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPUActionPerformed(evt);
            }
        });
        panelPalabra.add(textCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 0, 10));

        labelDinero.setBackground(new java.awt.Color(255, 255, 255));
        labelDinero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDinero.setText("Dinero acumulado: ");
        labelDinero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelDinero.setOpaque(true);
        panelPalabra.add(labelDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 170, 25));

        textDinero.setEditable(false);
        textDinero.setBackground(new java.awt.Color(255, 255, 255));
        textDinero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textDinero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDinero.setText("0");
        textDinero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPalabra.add(textDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 75, 210, 25));

        getContentPane().add(panelPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 380, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFiguraAhorcadoCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelFiguraAhorcadoCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 450, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFiguraAhorcadoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelFiguraAhorcadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 450, 450));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/WallpaperAhorcado.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1024, 700));
        jLabel8.setMinimumSize(new java.awt.Dimension(1024, 700));
        jLabel8.setPreferredSize(new java.awt.Dimension(1024, 700));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPartidaActionPerformed
        // TODO add your handling code here:
        conahor.eleccionPalabra();
        activarBotones();
    }//GEN-LAST:event_botonNuevaPartidaActionPerformed

    private void textCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPUActionPerformed

    private void botonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonA;
    public javax.swing.JButton botonB;
    public javax.swing.JButton botonC;
    public javax.swing.JButton botonD;
    public javax.swing.JButton botonE;
    public javax.swing.JButton botonF;
    public javax.swing.JButton botonG;
    public javax.swing.JButton botonH;
    public javax.swing.JButton botonI;
    public javax.swing.JButton botonJ;
    public javax.swing.JButton botonK;
    public javax.swing.JButton botonL;
    public javax.swing.JButton botonM;
    public javax.swing.JButton botonN;
    public javax.swing.JButton botonNuevaPartida;
    public javax.swing.JButton botonO;
    public javax.swing.JButton botonP;
    public javax.swing.JButton botonQ;
    public javax.swing.JButton botonR;
    public javax.swing.JButton botonS;
    public javax.swing.JButton botonSalir;
    public javax.swing.JButton botonT;
    public javax.swing.JButton botonU;
    public javax.swing.JButton botonV;
    public javax.swing.JButton botonW;
    public javax.swing.JButton botonX;
    public javax.swing.JButton botonY;
    public javax.swing.JButton botonZ;
    public javax.swing.JButton botonÑ;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel labelDinero;
    public javax.swing.JLabel labelErroresCPU;
    public javax.swing.JLabel labelErroresUsuario;
    public javax.swing.JLabel labelFiguraAhorcadoCPU;
    public javax.swing.JLabel labelFiguraAhorcadoUsuario;
    public javax.swing.JLabel labelPanelCPU;
    public javax.swing.JLabel labelPanelUsuario;
    public javax.swing.JLabel labelTitulo;
    public javax.swing.JPanel panelLetras;
    public javax.swing.JPanel panelPalabra;
    public javax.swing.JTextField textCPU;
    public javax.swing.JTextField textDinero;
    public javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
