/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Fernando
 */
public class VistaLogInFrame extends javax.swing.JFrame {
    public String dinero;
    public String[] personaje;

    /**
     * Creates new form VistaLogInFrame
     */
    public VistaLogInFrame() {
        initComponents();
        panelVistaPrincipal.setVisible(false);
        
    }
    public void addListenersLgin(ActionListener a){
        botonAceptar.addActionListener(a);
        botonRegistrarse.addActionListener(a);
    }
    public void quitarListenersLgin(ActionListener i){
        botonAceptar.removeActionListener(i);
        botonRegistrarse.removeActionListener(i);
    }
    public void addListenersVp(ActionListener e){
        //Batalla
        jButton1.addActionListener(e);
        //Biblioteca
        jButton2.addActionListener(e);
        //Inventario
        jButton3.addActionListener(e);
        //EAO
        jButton4.addActionListener(e);
        //Foro
        jButton5.addActionListener(e);
        //Malla
        jButton8.addActionListener(e);
    }
    public void vaciarCajas(){
        this.userField.setText("");
        this.passField.setText("");
    }
    
    public void cambiarVista(){
        panelLogIn.setVisible(false);
        panelVistaPrincipal.setVisible(true);
        jTextField2.setText("12.000");
    }
    
    public void imprimirPj(String[] personaje, String plataUser) {
        this.personaje = personaje;
        this.dinero = (plataUser);
        jTextField1.setText(personaje[1]);
        //dinero
        jTextField2.setText(dinero);
        //
        jTextField3.setText(personaje[5]);
        jTextField4.setText(personaje[6]);
        jTextField5.setText(personaje[7]);
        jTextField6.setText(personaje[8]);
        ImageIcon fotoPj = new ImageIcon(this.getClass().getResource(personaje[9]));
        labelFoto.setIcon(fotoPj);
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelVistaPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn");
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogIn.setBackground(new java.awt.Color(0, 0, 0));
        panelLogIn.setForeground(new java.awt.Color(240, 240, 240));
        panelLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelLogIn.setMaximumSize(new java.awt.Dimension(1024, 700));
        panelLogIn.setMinimumSize(new java.awt.Dimension(1024, 700));
        panelLogIn.setPreferredSize(new java.awt.Dimension(1024, 700));
        panelLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre de Usuario:");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        panelLogIn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 240, 30));

        userField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        userField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userField.setMaximumSize(null);
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        panelLogIn.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 240, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña:");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setOpaque(true);
        panelLogIn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 240, 30));

        passField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        passField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passField.setMaximumSize(null);
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        panelLogIn.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 240, 30));

        botonAceptar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoVerde.png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panelLogIn.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 220, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Aún no eres usuario?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelLogIn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 240, 30));

        botonRegistrarse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoAzul.png"))); // NOI18N
        botonRegistrarse.setText("¡Regístrate!");
        botonRegistrarse.setActionCommand("Registrarse");
        botonRegistrarse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });
        panelLogIn.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonDerVis.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        panelLogIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 50, 30));

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("¡Bienvenid@ a Hope-RPG!");
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelTitulo.setOpaque(true);
        panelLogIn.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 490, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOSF250.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        panelLogIn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 220, 220));

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoRojo.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelLogIn.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 643, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/ForoWall.jpg"))); // NOI18N
        panelLogIn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        getContentPane().add(panelLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelVistaPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        panelVistaPrincipal.setEnabled(false);
        panelVistaPrincipal.setMaximumSize(new java.awt.Dimension(1024, 700));
        panelVistaPrincipal.setMinimumSize(new java.awt.Dimension(1024, 700));
        panelVistaPrincipal.setPreferredSize(new java.awt.Dimension(1024, 700));
        panelVistaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EAO");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        panelVistaPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBatallaBla150.png"))); // NOI18N
        jButton1.setToolTipText("Accede a la Batalla para completar el juego");
        jButton1.setActionCommand("Batalla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 150, 150));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblioBla100.png"))); // NOI18N
        jButton2.setToolTipText("Accede a la Biblioteca Central y gana dinero para tus batallas");
        jButton2.setActionCommand("Biblioteca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 100, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InventarioBla100.png"))); // NOI18N
        jButton3.setToolTipText("Accede al Inventario y administra tus ítems y los de tu equipo");
        jButton3.setActionCommand("Inventario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 100, 100));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoEAOBla100.png"))); // NOI18N
        jButton4.setToolTipText("Accede a la EAO y compra ítems para tus batallas");
        jButton4.setActionCommand("EAO");
        jButton4.setAlignmentY(0.0F);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(221, 197));
        jButton4.setMinimumSize(new java.awt.Dimension(221, 197));
        jButton4.setPreferredSize(new java.awt.Dimension(265, 197));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 100, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ForoBla100.png"))); // NOI18N
        jButton5.setToolTipText("Accede al Foro Griego y contrata aliados para tus batallas");
        jButton5.setActionCommand("ForoGriego");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 100, 100));

        labelFoto.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelFoto.setOpaque(true);
        panelVistaPrincipal.add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, 100));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dinero:");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        panelVistaPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 120, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ataque:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        panelVistaPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 120, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Vida:");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);
        panelVistaPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 120, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Escudo:");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);
        panelVistaPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 120, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Magia:");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);
        panelVistaPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 120, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nick:");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);
        panelVistaPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Foro Griego");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);
        panelVistaPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 140, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Batalla");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setOpaque(true);
        panelVistaPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 150, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Biblioteca Central");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setOpaque(true);
        panelVistaPrincipal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 140, 30));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Inventario Jugador");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24.setOpaque(true);
        panelVistaPrincipal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 140, 30));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVistaPrincipal.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 120, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVistaPrincipal.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 120, 30));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVistaPrincipal.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 120, 30));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVistaPrincipal.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 120, 30));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVistaPrincipal.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 120, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Malla Curricular");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);
        panelVistaPrincipal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 140, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MallBlack100.png"))); // NOI18N
        jButton8.setToolTipText("Accede a la Malla Curricular y verifica tu avance en el juego");
        jButton8.setActionCommand("Malla Curricular");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUSACHitaBla.png"))); // NOI18N
        panelVistaPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 100, 100));

        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoRojo.png"))); // NOI18N
        jButton7.setText("Salir");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelVistaPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, 100, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVP.png"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelVistaPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        getContentPane().add(panelVistaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //Abrir malla
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Abrir foro griego
        //VistaForoGriego visForGr = new VistaForoGriego(this, true,id_Usuario);
        //visForGr.setLocationRelativeTo(this);
        //visForGr.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Abrir EAO
        //VistaEAO visEAO = new VistaEAO(this, true);
        //visEAO.setLocationRelativeTo(this);
        //visEAO.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Abrir inventario
        //VistaInventario visInv = new VistaInventario(this,true);
        //visInv.setLocationRelativeTo(this);
        //visInv.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //MiniJuegosJDialog biblioteca = new MiniJuegosJDialog(this,true,id_Usuario);
        //biblioteca.setLocationRelativeTo(this);
        //biblioteca.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        // TODO add your handling code here:
        //ControladorLogIn conlog = new ControladorLogIn();
        //conlog.registrarse();
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    /*.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAceptar;
    public javax.swing.JButton botonRegistrarse;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel labelFoto;
    public javax.swing.JPanel panelLogIn;
    public javax.swing.JPanel panelVistaPrincipal;
    public javax.swing.JPasswordField passField;
    public javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables

    

    
}
