/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import java.awt.event.*;

import Controladores.ControladorTablero;

/**
 *
 * @author Fernando
 */
public class VistaTableroDialog extends javax.swing.JDialog  {
   

    /**
     * Creates new form vistaTablero
     * @param parent
     * @param modal
     * @param contab
     */
    
   
     public VistaTableroDialog(java.awt.Frame parent, boolean modal,ControladorTablero contab) {
        super(parent, modal);
        initComponents();
        //initComponents();
        
        
    }
     
    public void agregarListeners(ActionListener A){
        this.jButton1.addActionListener(A);
        this.jButton2.addActionListener(A);
        this.jButton3.addActionListener(A);
        this.jButton4.addActionListener(A);
        this.jButton5.addActionListener(A);
        this.jButton6.addActionListener(A);
        this.jButton7.addActionListener(A);
        this.jButton8.addActionListener(A);
        this.jButton9.addActionListener(A);
        this.jButton10.addActionListener(A);
        this.jButton11.addActionListener(A);
        this.jButton12.addActionListener(A);
        this.jButton13.addActionListener(A);
        this.jButton14.addActionListener(A);
        this.jButton15.addActionListener(A);
        this.jButton16.addActionListener(A);
        this.jButton17.addActionListener(A);
        
    }
    


    /**
     * Creates new form VistaTableroDialog
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Batalla");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1264, 700));
        setMinimumSize(new java.awt.Dimension(1264, 700));
        setPreferredSize(new java.awt.Dimension(1264, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1264, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 570, 120));

        jButton17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton17.setText("Ver jugadores y datos del tablero");
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 310, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1007, 140));

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setPreferredSize(new java.awt.Dimension(225, 468));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 206, 219));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vida");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ataque");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Defensa");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Movimientos");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 20));

        jLabel6.setOpaque(true);
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 236, 102, 19));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, 20));

        jProgressBar1.setForeground(new java.awt.Color(51, 0, 255));
        panel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 90, 20));

        jProgressBar2.setForeground(new java.awt.Color(255, 0, 102));
        panel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 20));

        jProgressBar3.setForeground(new java.awt.Color(0, 153, 153));
        panel1.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 90, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/arriba.png"))); // NOI18N
        panel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 63, 24));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/izquierda.png"))); // NOI18N
        panel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 63, 24));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/derecha.png"))); // NOI18N
        panel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 63, 24));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/dg_ar_i.png"))); // NOI18N
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 63, 23));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/dg_ar_d.png"))); // NOI18N
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 63, 24));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/dg_a_d.png"))); // NOI18N
        panel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 63, 24));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/dg_a_i.png"))); // NOI18N
        panel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 63, 24));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/abajo.png"))); // NOI18N
        panel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 63, 24));

        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setText("Mover");
        panel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, 20));

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("Atacar");
        panel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, 20));

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("Usar Item");
        panel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 90, 20));

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("Largo Alcance");
        panel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, -1));

        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setText("Corto Alcance");
        panel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, -1));

        jButton14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton14.setText("Cancelar");
        panel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 90, 20));

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        panel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 20));

        jButton15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton15.setText("Atacar");
        panel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 20));

        panel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 40, -1));
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 10, 10));

        jButton16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton16.setText("Pasar");
        panel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 90, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, -1, 660));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public void cancelar(){
        jButton11.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        jComboBox1.setVisible(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    public javax.swing.JButton jButton15;
    public javax.swing.JButton jButton16;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JProgressBar jProgressBar2;
    public javax.swing.JProgressBar jProgressBar3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    public void cerrarVista() {
        this.dispose();
    }

    

    

  
}
