/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorRegistro;
import Modelos.ModeloUsuario;
import Modelos.Personaje;
import javax.swing.JDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author Fernando
 */
public class VistaRegistro extends javax.swing.JDialog {
    ControladorRegistro conreg;
    
    int pj;
    int mjamg_pj;
    int idJugadorRegistrado;
    private Personaje personaje;

    /**
     * Creates new form VistaRegistro
     * @param parent
     * @param modal
     * @param conreg
     * @param personaje
     */
    public VistaRegistro(java.awt.Frame parent, boolean modal, ControladorRegistro conreg, Personaje personaje) {
        super(parent, modal);
        initComponents();    
        this.conreg = conreg;
        this.personaje = personaje;
        panel.setVisible(false);
    
    }

    public VistaRegistro() {
     }
    private void solicitarPersonaje(String selectedItem) {
        String[] personaje = conreg.buscarPersonaje(selectedItem).split("CORTAR");
        jLabel2.setText(personaje[0]);
        jLabel7.setText(personaje[1]);
        int vida = Integer.parseInt(personaje[4]);
        int defensa = Integer.parseInt(personaje[5]);
        int ataque = Integer.parseInt(personaje[6]);
        int movimiento = Integer.parseInt(personaje[7]);
        int magia = Integer.parseInt(personaje[8]);
        ImageIcon fotoPj = new ImageIcon(this.getClass().getResource(personaje[9]));
        labelCara.setIcon(fotoPj);
        barra1.setMaximum(vida); barra1.setValue(vida); barra1.setString(personaje[4]);
        barra2.setMaximum(defensa); barra2.setValue(defensa);barra2.setString(personaje[5]);
        barra3.setMaximum(ataque); barra3.setValue(ataque);barra3.setString(personaje[6]);
        barra4.setMaximum(movimiento); barra4.setValue(movimiento);barra4.setString(personaje[7]);
        barra5.setMaximum(magia); barra5.setValue(magia);barra5.setString(personaje[8]);
    }

    
    
    public void addListener(ActionListener a){
        botonCancelar.addActionListener(a);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labelCara = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        barra1 = new javax.swing.JProgressBar();
        barra2 = new javax.swing.JProgressBar();
        barra3 = new javax.swing.JProgressBar();
        barra4 = new javax.swing.JProgressBar();
        barra5 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        botonSalir1 = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        comboBoxCarreras = new javax.swing.JComboBox<>();
        labelPass = new javax.swing.JLabel();
        comboBoxRoles = new javax.swing.JComboBox<>();
        labelPass2 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        passField2 = new javax.swing.JPasswordField();
        passField1 = new javax.swing.JPasswordField();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.setMaximumSize(new java.awt.Dimension(1024, 700));
        panel.setMinimumSize(new java.awt.Dimension(1024, 700));
        panel.setPreferredSize(new java.awt.Dimension(1024, 700));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCara.setBackground(new java.awt.Color(255, 255, 255));
        labelCara.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        labelCara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NN.png"))); // NOI18N
        labelCara.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.add(labelCara, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 100, 100));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 180, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Puntos de Vida");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 260, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Puntos de Defensa");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 260, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Puntos De Ataque");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 260, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Puntos Magicos");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setOpaque(true);
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 260, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Movimiento");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 260, 30));

        barra1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra1.setStringPainted(true);
        panel.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 270, 30));

        barra2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra2.setStringPainted(true);
        panel.add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 270, 30));

        barra3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra3.setStringPainted(true);
        panel.add(barra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 270, 30));

        barra4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra4.setStringPainted(true);
        panel.add(barra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 270, 30));

        barra5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra5.setStringPainted(true);
        panel.add(barra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 270, 30));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoAmarillo.png"))); // NOI18N
        jButton1.setText("Buscar nuevo personaje");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 260, 30));

        botonSalir1.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonSalir1.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojo.png"))); // NOI18N
        botonSalir1.setText("Salir");
        botonSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir1ActionPerformed(evt);
            }
        });
        panel.add(botonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, 100, 30));

        jLabelTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("PASO 1: Elección de Personaje");
        jLabelTitulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setOpaque(true);
        panel.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 790, 50));

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoAzul.png"))); // NOI18N
        jButton2.setText("Siguiente");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 150, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 20));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoVerde.png"))); // NOI18N
        jButton3.setText("Finalizar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 150, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Personaje Principal:");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 260, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/ForoWall.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(1024, 700));
        jLabel5.setMinimumSize(new java.awt.Dimension(1024, 700));
        jLabel5.setPreferredSize(new java.awt.Dimension(1024, 700));
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setMaximumSize(new java.awt.Dimension(1024, 700));
        panel2.setMinimumSize(new java.awt.Dimension(1024, 700));
        panel2.setPreferredSize(new java.awt.Dimension(1024, 700));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        panel2.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 230, 30));

        labelNombre.setBackground(new java.awt.Color(0, 0, 0));
        labelNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre usuario: ");
        labelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelNombre.setOpaque(true);
        panel2.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 230, 30));

        labelCarrera.setBackground(new java.awt.Color(0, 0, 0));
        labelCarrera.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCarrera.setForeground(new java.awt.Color(255, 255, 255));
        labelCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCarrera.setText("Carrera:");
        labelCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelCarrera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelCarrera.setOpaque(true);
        panel2.add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 230, 30));

        comboBoxCarreras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comboBoxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing. Ejecución", "Ing. Civil" }));
        comboBoxCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCarrerasActionPerformed(evt);
            }
        });
        panel2.add(comboBoxCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 230, 30));

        labelPass.setBackground(new java.awt.Color(0, 0, 0));
        labelPass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelPass.setForeground(new java.awt.Color(255, 255, 255));
        labelPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPass.setText("Contraseña usuario:");
        labelPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelPass.setOpaque(true);
        panel2.add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 230, 30));

        comboBoxRoles.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comboBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Guerrero" }));
        comboBoxRoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        comboBoxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRolesActionPerformed(evt);
            }
        });
        panel2.add(comboBoxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 230, 30));

        labelPass2.setBackground(new java.awt.Color(0, 0, 0));
        labelPass2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelPass2.setForeground(new java.awt.Color(255, 255, 255));
        labelPass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPass2.setText("Repite la contraseña:");
        labelPass2.setToolTipText("");
        labelPass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelPass2.setOpaque(true);
        panel2.add(labelPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 230, 30));

        labelRol.setBackground(new java.awt.Color(0, 0, 0));
        labelRol.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRol.setForeground(new java.awt.Color(255, 255, 255));
        labelRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRol.setText("Rol:");
        labelRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelRol.setOpaque(true);
        panel2.add(labelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 230, 30));

        passField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel2.add(passField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 230, 30));

        passField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel2.add(passField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 230, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoNaranjo.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panel2.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 230, 30));

        botonAceptar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFinales/FondoVerde.png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panel2.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 230, 30));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojo.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panel2.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 100, 30));

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Registro");
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelTitulo.setOpaque(true);
        panel2.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 370, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/ForoWall.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1024, 700));
        jLabel4.setMinimumSize(new java.awt.Dimension(1024, 700));
        jLabel4.setPreferredSize(new java.awt.Dimension(1024, 700));
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mjamg_pj = Integer.parseInt(jLabel2.getText());
       
        personaje.modificarTraicion(pj, 0);
        personaje.modificarTraicion(mjamg_pj, 0);
        conreg.insertarPersonaje(pj,mjamg_pj,idJugadorRegistrado);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabelTitulo1.setText("PASO 2: ELIGE A TU ACOMPAÑANTE");
        JOptionPane.showMessageDialog(this, "Muy bien! Ahora elige a tu mejor amigo.", "Sigamos..", JOptionPane.INFORMATION_MESSAGE);
        jLabel3.setText("Eleccion de mejor amigo:");
        pj = Integer.parseInt(jLabel2.getText());
        jButton2.setVisible(false);
        jButton3.setVisible(true);
        solicitarPersonaje("none");
    }//GEN-LAST:event_jButton2ActionPerformed

    /*    */
    private void botonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton3.isVisible()){
            solicitarPersonaje("none");
            
        }else{
            solicitarPersonaje(this.comboBoxRoles.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String nombre = userField.getText();
        int id_rol = comboBoxRoles.getSelectedIndex()+1;
        String pass = passField1.getText();
        String passConf = passField2.getText();
        int id_carrera = comboBoxCarreras.getSelectedIndex()+1;
        boolean completo = conreg.obtenerDatos(nombre, id_rol, pass, passConf, id_carrera);
        if (completo){
            // por mover a controlador
            idJugadorRegistrado = conreg.obtenerUltimaID();
            
            solicitarPersonaje(this.comboBoxRoles.getSelectedItem().toString());
            panel.setVisible(true);
            panel2.setVisible(false);
            jButton3.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Registro incompleto. Porfavor, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboBoxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRolesActionPerformed

    private void comboBoxCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCarrerasActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra1;
    private javax.swing.JProgressBar barra2;
    private javax.swing.JProgressBar barra3;
    private javax.swing.JProgressBar barra4;
    private javax.swing.JProgressBar barra5;
    public javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JComboBox<String> comboBoxCarreras;
    private javax.swing.JComboBox<String> comboBoxRoles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel labelCara;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPass2;
    private javax.swing.JLabel labelRol;
    private javax.swing.JPanel panel;
    public javax.swing.JPanel panel2;
    public javax.swing.JPasswordField passField1;
    private javax.swing.JPasswordField passField2;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables

    
}
